import Head from 'next/head'
import Image from "next/image";
import styles from '@/styles/Home.module.css'
import Banner from "@/components/banner";
import Card from "@/components/card";
import {getCoffeeShops} from "@/lib/coffee-store";


export async function getStaticProps(context) {
  const coffeeStores = await getCoffeeShops();
  return {
    props: {
      coffeeStores,
    }, // will be passed to the page component as props
  };
}

export default function Home({coffeeStores}) {

  const handleBanerBtnClick = () => {
    console.log('Btn Clicked');
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <Banner btnText="View stores nearby"
                handleOnClick={handleBanerBtnClick}/>
        <div className={styles.heroImage}>
          <Image alt="coffee image" src="/static/hero-image.png" width={700} height={400}/>
        </div>
        {coffeeStores.length > 0 && (<>
          <h2 className={styles.heading2}>Toronto Stores</h2>
          <div className={styles.cardLayout}>
            {coffeeStores.map(coffeeStore => {
              return (<Card
                key={coffeeStore.id}
                name={coffeeStore.name}
                imgUrl={coffeeStore.imgUrl || 'https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80'}
                href={`/coffee-store/${coffeeStore.id}`}
                className={styles.card}
              />)
            })}
          </div>
        </>)}

      </main>
    </>
  )
}
